name: AMI Build

on:
  pull_request:
    types:
      - closed
    branches:
        - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: AMI Build
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Abhi$3534
          MYSQL_DATABASE: cloudschema
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

          
      - name: Install dependencies check
        run: npm install

      - name: Run testing
        run: npm test

      - name: "Setup .env file"
        run: |
          touch .env
          echo PGDATABASE="abcd" >> .env

      - name: Run tests
        run: npm run test

      - name: Zip Repository
        run: |
          zip -r webapp.zip . .env
          mkdir -p zip
          mv webapp.zip zip/

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run Packer init
        id: init
        run: |
          packer init packer.pkr.hcl

      - name: Build AMI
        run: |
            packer build -var "artifact=zip/webapp.zip" packer.pkr.hcl