name: Check Packer Format and Validate

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: validate and fmt for packer
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      id  : setup
      with:
        version : latest

    - name: Initialize Packer
      run: packer init .
    
    - name: Run Packer format check
      uses: packer fmt -check=true

    - name: Validate Packer Config
      run: packer validate packer.pkr.hcl
        

