name: Packer Format Check

on:
  pull_request:
    branches:
        main
    types:
      - opened
      - synchronize

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
        if: success()

      - name: Run Packer fmt
        run: |
          packer fmt .
        if: success()
