name: Check Packer Validate

on: 
  pull_request:
    branches:
      - main

jobs:
  validate_packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main

    - name: Validate Packer Config
      run: packer validate packer.pkr.hcl
        

