name: Packer Validate

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  validate_packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main

    - name: Validate Packer Config
      run: packer validate packer.pkr.hcl
        

